# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 038ef8741737f44aba1276ff2575d1d4a0640b4b927640a20d9676a7ef62e2bca7b79555cf3252d834d0f570b08e9ff756316154a4382fce22e4c4a4ff477f99

test:
  secret_key_base: a8f1f2388bfb08e00d0aa4d2ba2a10ea994c9b03b8e2594b88ac871a126d48b3887ab74915a7e37867922a8ae6baa07cb0a3800057c234c9197eafe9c4c82a78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
